### ISSUE TITLE
turf.intersect fails in 3.0.5

### ISSUE THREAD

**Issue by kragoth** [Turfjs/turf#412]
I have a [jsfiddle example](https://jsfiddle.net/cLe6yo9d/2/) here of turf.intersect failing

If you click the button that says "Click me - I fail" and look in the developer tools console you will see:
`Uncaught TypeError: this.seg.p1.equals2D is not a function`

However, if I run a `turf.simplify(polygon2, 0.00001, false)` as seen by clicking on the button that says "Click me - I work because Im simple" the intersect function is successful.

I dug down a bit and there appears to be multiple problems.
It appears that the reason for the "equals2D is not a function" is because in the snapSegments an add function is called that is adding the index to the array as an element instead of the object that contains the coords and functions.

I went and fixed this in my code and tried again but, it just fails again because once again the snapSegments causes the creation of an invalid polygon.

I've had to do this all with the minified turfjs lib so I can't tell you the line of code that the failure is on. I can't seem to find a way of getting a non minified version. Most of the links in the documentation are wrong/broken or do not point to the latest version of turf.

This example works fine in turf 2.0.0 as seen on this [jsFiddle example](https://jsfiddle.net/cLe6yo9d/3/)

**Comment by drewbo** [comment]
I'm seeing the same error when using `turf-union` though I don't have a nice reproducible example (yet). The error is being thrown from the underlying `jsts` dependency which seems to have a [similar reported issue](https://github.com/bjornharrtell/jsts/issues/273)? Having the turf modules update to the most recent `jsts` version (`1.2.0`) may resolve some of this

**Comment by Skripatch** [comment]
Faced with the same bug

**Comment by codeofsumit** [comment]
Same here
![image](https://cloud.githubusercontent.com/assets/2399810/17922670/7ebd96a0-69e0-11e6-8d2d-eabdca620160.png)

**Comment by drewbo** [comment]
Created a [failing test case on requirebin](http://requirebin.com/?gist=cc81e228b7aab04242cf0499ed38cf91) using turf-union. Error in the console is the dreaded `Uncaught TypeError: this.seg.p1.equals2D is not a function`. The two features are very similar circular-ish polygons the cover most of the same area (but not exactly; they were generated by using a large `turf-buffer` on two nearby points) cc: @anandthakker

**Comment by drewbo** [comment]
Randomly deleting almost all the vertices creates two triangles which still produce the error. It looks like one of the vertices (lower left in the link) is "directly" on the line of the other triangle which seems related

http://bl.ocks.org/d/fb2e1533c68f6274af501512911b0e45

**Comment by codeofsumit** [comment]
@drewbo using the latest version of turf this error disappeared but I get the self-intersect error you mentioned even if there are none. I'm using turf `difference` and `intersect` which both have this problem inside a try-catch block for now.

**Comment by clluiz** [comment]
Same problem here. Using intersect, I have this problem when the geometry is like:

![screenshot-geojson io 2016-09-06 08-18-23](https://cloud.githubusercontent.com/assets/1070968/18271827/a1fc8cfa-740a-11e6-9899-3d1b4daf4c50.png)

**Comment by DenisCarriere** [comment]
For any issues related to `@turf/intersect` submit a PR with a new GeoJSON Feature Collection with two polygons that should or should not intersect.

**Step 1:** Add polygon to [test/in](https://github.com/Turfjs/turf/tree/master/packages/turf-intersect/test/in)

**Step 2:** Run tests `npm test`

**Step 3:** If an error occurs, submit PR with new GeoJSON causing the error.

**Comment by drewbo** [comment]
@DenisCarriere looks like it throws a separate error if the polygon isn't also added to `test/out`:

`Error: ENOENT: no such file or directory, open '/Users/andrewbollinger/github-repos/turf/packages/turf-intersect/test/out/issue-412.geojson`

**Comment by drewbo** [comment]
Thanks @DenisCarriere This fixed the issue for my specific GeoJSON (I won't speak for other). Do you know which commit/broad change fixed this?

**Comment by DenisCarriere** [comment]
Oh forgot to mention to add the environment variable `REGEN=true`.

Thanks for the quick reply.

**Comment by DenisCarriere** [comment]
No idea what could of been the fix, maybe `jsts` got fixed.

Dont' hesitate to send over your `test/in`, even if it's valid, this will help validate the next module whenever we drop `jsts` as a dependency.

**Comment by DenisCarriere** [comment]
@drewbo Oh and if you want to Format the GeoJSON into a "pretty" format, you can add it to http://geojson.io and (CTRL+S) to save & copy paste the results.

**Comment by drewbo** [comment]
Ha, this was ironically create from geojson.io then shared (which writes it to a gist as a one-liner). Opened as https://github.com/Turfjs/turf/pull/605 but happy to update

**Comment by DenisCarriere** [comment]
Oh that's pretty ironic! No worries 👍 one line or multi line is fine.
